### ISSUE TITLE
Cant install nuget

### ISSUE THREAD

**Issue by tekadept** [ScottKaye/CoreRCON#4]
Hi when i try and install Nuget i get an error below
CoreRCON 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package 
does not contain any assembly references or content files that are compatible with that framework.

I have tried changing the target framework to what i think is every option but still cannot get it to install. Can you please advise what framework It is targeted to in case i missed one?

**Comment by ScottKaye** [comment]
I probably screwed up the project.json - currently the supported frameworks are .NET Core 1.0 and 1.1.  Since VS2017, there's been some changes to how the project file is made.  I'm unfortunately not really maintaining this project as I don't play TF2/CSGO anymore, but PRs are definitely welcome.

Note to self: I probably have to add [`net452`](https://blogs.msdn.microsoft.com/cesardelatorre/2016/06/28/running-net-core-apps-on-multiple-frameworks-and-what-the-target-framework-monikers-tfms-are-about/) to the project.json.

**Comment by goigle** [comment]
You can try and follow these steps to reference the compiled library:
https://stackoverflow.com/a/40042611
However:
I tried adding "dnx46": {} to the project.json but it's giving me some errors that appear to be because of differences in version:
Argument 1: cannot convert from 'System.Net.IPEndPoint' to 'System.Net.Sockets.SocketAsyncEventArgs'	CoreRCON	CoreRCON\RCON.cs:62	

and another about no overload with 2 arguments in Socket.SendAsync, which appears to match up here:
https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.sendasync(v=vs.110).aspx

This is kind of over my head so I don't really know how to fix this.

For the one with 'no two overloads' (150 on RCON.cs), I have tried creating the SocketAsyncEventArgs myself. I can set the buffer by doing this:
```
            SocketAsyncEventArgs args = new SocketAsyncEventArgs();
            args.SetBuffer(packet.ToBytes(), 0, 0);
```

but it needs an offset and a count, and I don't know what to set those to.

The first one can be fixed just by creating the args and setting the endpoint, but then it throws another error about not having a GetAwaiter()
